import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} flex flex-col min-h-screen`}>
          <header className="flex flex-col items-center justify-start w-full">
            <SignedOut>
              <div className="flex justify-center items-center h-screen">
                <SignInButton />
              </div>
            </SignedOut>
            <SignedIn>
              <div className="mt-4 flex justify-center w-full">
                <UserButton />
              </div>
            </SignedIn>
          </header>
          <main className="flex-1 flex justify-center items-center">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
